//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceWizard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceWizard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aq {
            get {
                object obj = ResourceManager.GetObject("aq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap colors {
            get {
                object obj = ResourceManager.GetObject("colors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap components {
            get {
                object obj = ResourceManager.GetObject("components", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete2 {
            get {
                object obj = ResourceManager.GetObject("delete2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бастет,Клёпа,Лаура,Тинга,Уда,Сузани,Муня,Нитка,Чая,Рэда,Сапфирина,Лика,Рича,Швабра,Сандра,Тайша,Аюта,Жека,Улана,Асла,Авиаджи,Луиза,Алько,Аэлита,Чарда,Санта,Крыса,Олери,Санда,Жанетта,Чанита,Экса,Барса,Сэтти,Бени,Луша,Вето,Герда,Тася,Анчута,Ешка,Китася,Йоланта,Лаванда,Фемида,Руста,Саламбо,Енса,Сентап,Целли,Твити,Миля,Капитолина,Мава,Тушка,Ундина,Буна,Мелисса,Юда,Арга,Кинель,Ара,Криза,Фалька,Альджетта,Жалли,Лекси,Фелика,Жеси,Охра,Йаки,Юрга,Креди,Мышка,Рифка,Хильда,Фрося,Жасмин,Илга,Тойра,Цанта,Хальта,Аремо,Даф [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string femalenicks {
            get {
                return ResourceManager.GetString("femalenicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gold_plated_16x16 {
            get {
                object obj = ResourceManager.GetObject("gold_plated_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эйх,Витас,Жанно,Балли,Брэн,Асик,Бор,Саган,Додсон,Соллекс,Шашлык,Мурзилка,Чингисхан,Файлик,Цитрон,Азаделло,Холл,Хрюндель,Хиппи,Гермес,Ачи,Плакун,Натан,Космос,Цзянь,Клод,Курбет,Экко,Мейчи,Чебурашка,Карпет,Арамис,Джем,Драг,Пуник,Сокол,Шарж,Зоркий,Чубайс,Джамбо,Стёпа,Малыш,Ферри,Оззи,Цыган,Джерри,Шек,Бори,Бэтмэн,Иф,Зенто,Том,Нафан,Сильвестр,Берот,Акила,Рабинович,Кронос,Экбар,Лэк,Ченз,Гирольд,Жулан,Шах,Бабот,Спаси,Дьюк,Ромка,Фаде,Шико,Динь,Легарт,Елор,Дарс,Дракон,Конкорд,Бернард,Стэк,Кеззи,Шейх,Зели,Шаян,Сатурн, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string malenicks {
            get {
                return ResourceManager.GetString("malenicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap navigate_left {
            get {
                object obj = ResourceManager.GetObject("navigate_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap navigate_right {
            get {
                object obj = ResourceManager.GetObject("navigate_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nethack {
            get {
                object obj = ResourceManager.GetObject("nethack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Phoebus_16x16 {
            get {
                object obj = ResourceManager.GetObject("Phoebus_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RantingRodent_Brick_01 {
            get {
                object obj = ResourceManager.GetObject("RantingRodent_Brick_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RantingRodent_Brick_02 {
            get {
                object obj = ResourceManager.GetObject("RantingRodent_Brick_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RantingRodent_Natural_01 {
            get {
                object obj = ResourceManager.GetObject("RantingRodent_Natural_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RantingRodent_Natural_02 {
            get {
                object obj = ResourceManager.GetObject("RantingRodent_Natural_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redjack15v {
            get {
                object obj = ResourceManager.GetObject("redjack15v", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ultima4 {
            get {
                object obj = ResourceManager.GetObject("Ultima4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ultima5 {
            get {
                object obj = ResourceManager.GetObject("Ultima5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yinyang {
            get {
                object obj = ResourceManager.GetObject("yinyang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
